document.addEventListener('DOMContentLoaded', function () {
  var tipoAtual = 'doador';
  var tabDoador = document.getElementById('tabDoador'); var tabColetor = document.getElementById('tabColetor'); var titulo = document.getElementById('loginTitulo'); var texto = document.getElementById('loginTexto'); var label = document.getElementById('labelIdentificador'); var identificador = document.getElementById('identificador'); var senha = document.getElementById('senha'); var lembrar = document.getElementById('lembrar'); var link = document.getElementById('linkCadastro'); var form = document.getElementById('formLogin');
  var textos = { doador: { titulo: 'Acesse sua conta', texto: 'Entre para gerenciar seus materiais e solicitar coletas.', label: 'E-mail ou telefone', placeholder: 'voce@email.com ou (11) 99999-9999', link: 'Criar conta de doador', href: 'cadastro-doador.html' }, coletor: { titulo: 'Acesse sua conta de coletor', texto: 'Entre para gerenciar suas coletas e materiais.', label: 'CPF ou e-mail', placeholder: '000.000.000-00 ou voce@email.com', link: 'Criar conta de coletor', href: 'cadastro-coletor.html' } };
  function preencherLembrado() { var salvo; try { salvo = JSON.parse(localStorage.getItem(DB_KEYS.lembrar)); } catch (e) { salvo = null; } identificador.value = salvo && salvo.tipo === tipoAtual ? salvo.identificador : ''; lembrar.checked = !!(salvo && salvo.tipo === tipoAtual); }
  function selecionarTipo(tipo) { tipoAtual = tipo; var atual = textos[tipo]; titulo.textContent = atual.titulo; texto.textContent = atual.texto; label.textContent = atual.label; identificador.placeholder = atual.placeholder; link.textContent = atual.link; link.href = atual.href; tabDoador.classList.toggle('active', tipo === 'doador'); tabColetor.classList.toggle('active', tipo === 'coletor'); tabDoador.setAttribute('aria-selected', String(tipo === 'doador')); tabColetor.setAttribute('aria-selected', String(tipo === 'coletor')); limparErros(form); esconderAlerta(); preencherLembrado(); }
  tabDoador.addEventListener('click', function () { selecionarTipo('doador'); }); tabColetor.addEventListener('click', function () { selecionarTipo('coletor'); }); preencherLembrado();
  var msg = sessionStorage.getItem('ecomaps_msg'); if (msg) { mostrarAlerta(msg, 'sucesso'); sessionStorage.removeItem('ecomaps_msg'); var msgTipo = sessionStorage.getItem('ecomaps_msg_tipo'); if (msgTipo) selecionarTipo(msgTipo); sessionStorage.removeItem('ecomaps_msg_tipo'); }
  form.addEventListener('submit', function (event) { event.preventDefault(); limparErros(form); esconderAlerta(); var id = identificador.value.trim(); var pass = senha.value; if (!id) mostrarErro('identificador', 'erroIdentificador', 'Informe seu ' + textos[tipoAtual].label.toLowerCase() + '.'); if (!pass) mostrarErro('senha', 'erroSenha', 'Informe sua senha.'); if (!id || !pass) return; var chave = tipoAtual === 'coletor' ? DB_KEYS.coletores : DB_KEYS.doadores; var busca = id.toLowerCase(); var numeros = somenteNumeros(id); var usuario = dbLer(chave).find(function (u) { return (u.email || '').toLowerCase() === busca || (numeros && somenteNumeros(u.telefone || '') === numeros) || (numeros && somenteNumeros(u.cpf || '') === numeros); }); if (!usuario || usuario.senha !== pass) { mostrarAlerta('E-mail, telefone, CPF ou senha incorretos.', 'erro'); return; } sessaoSalvar({ tipo: tipoAtual, id: usuario.id, nome: usuario.nome, logadoEm: new Date().toISOString() }); if (lembrar.checked) localStorage.setItem(DB_KEYS.lembrar, JSON.stringify({ tipo: tipoAtual, identificador: id })); else localStorage.removeItem(DB_KEYS.lembrar); window.location.href = tipoAtual === 'coletor' ? 'dashboard-coletor.html' : 'dashboard-doador.html'; });
});
