services:
  - type: web
    name: ecomap
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir Wall-E app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: false
